name = "buchiiyashi-festa-form"
main = "src/index.js"
compatibility_date = "2024-01-01"

# 環境変数（デプロイ時に設定）
[vars]
GAS_URL = "https://script.google.com/macros/s/AKfycbzjoA1ClbXURgas8tnlqtLy668rfMPQf7wX_ft_8Vo86pNeOFmXBI0kORblgRxdydwN/exec"
R2_PUBLIC_URL = "https://pub-6f861e123523d4086e2cc5a9943e6c12.r2.dev"

# R2バケットバインディング
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "buchiiyashi-images"
